package-lock.json
src/main/deps.cljs

Two moderate vulnerabilities in `ws` and `ansi-regex`

updated ansi-regex and ws

---

.github/workflows/main.yml
Makefile

Dependabot is nice but we only get alerts when code hits master. Add `npm audit` to the CI workflow so it fails if any sec issues are detected!

Audit npm in CI

---

.github/workflows/main.yml

This shows a possible route to standardizing CI environments. Things like matrices and actual commands ~~should probably not~~ _can not_ live in the composite action, or at least the same one. But this centralizes default versions and removes a BUNCH of repeat code from our actions.
See https://github.com/yetanalytics/yeti-ci-action for the composite action code

Gh action improvement

---

src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc

[LRS-57] Given the following multipart request containing lots of statements:
```http
POST /xapi/statements HTTP/1.1
X-Experience-API-Version: 1.0.3
Content-Type: multipart/mixed; boundary=105423a5219f5a63362a375ba7a64a8f234da19c7d01e56800c3c64b26bb2fa0
Host: localhost:8080
Connection: close
User-Agent: Paw/3.3.1 (Macintosh; OS X/11.6.0) GCDHTTPRequest
Content-Length: 45207
--105423a5219f5a63362a375ba7a64a8f234da19c7d01e56800c3c64b26bb2fa0
Content-Type:application/json
[{"actor":{"objectType":"Agent","name":"xAPI mbox","mbox":"mailto:xapi@adlnet.gov"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attended","display":{"en-GB":"attended","en-US":"attended"}},"object":{"objectType":"Activity","id":"http://www.example.com/meetings/occurances/34534"},"id":"72fbeb28-6a28-4117-b546-b936553c7adb"," …
```

Ensure statement JSON is completely consumed in multipart

---

CHANGELOG.md
package-lock.json
src/dev/mem_lrs/server.cljc

Sometimes it is useful to control the port of the in-memory development LRS. This modifies the `run-dev` function to take `HTTP_HOST` and `HTTP_PORT` from environment.

Allow environment configuration of dev in-memory LRS bind host and port

---

src/main/com/yetanalytics/lrs/impl/memory.cljc
src/main/com/yetanalytics/lrs/pedestal/routes/documents.cljc
src/main/com/yetanalytics/lrs/xapi/document.cljc

Update the content-length spec to reflect that it is nilable. 1.x says that the client [SHOULD* send it](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#header-parameters). ~~In 2.0 this should change to a MUST and the LRS should throw a 400 if no content-length is provided.~~
A client must _either_ send a `content-length` or `transfer-encoding: chunked` header. If they do the latter, the content length will not be known when the inputstream is passed to the impl. Additionally, the content-type may be left out of some documents so we pass this through to the impl.

Content-length and content-type are optional

---

resources/lrs/statements/style.css

[LRS-60] Our use of `align-items: baseline;` causes a tab crash on Chrome 95+. Use `align-items: center;` to not crash the browser.
NOTE: For the benefit of anyone chasing down the chrome issue and finding this, please see a static reproduction here: https://github.com/yetanalytics/lrs_css_bug_repro
A live demo can be found here: https://yetanalytics.github.io/lrs_css_bug_repro/
Click on the "8" to expand, tab will crash!
[LRS-60]: https://yet.atlassian.net/browse/LRS-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LRS-60 change align-items from baseline to center for map entries

---

src/dev/mem_lrs/service.cljc
src/main/com/yetanalytics/lrs.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc
src/main/com/yetanalytics/lrs/pedestal/routes.cljc
src/main/com/yetanalytics/lrs/pedestal/routes/documents.cljc
src/main/com/yetanalytics/lrs/protocol.cljc

Exception handling should be delegated to implementations based on their needs regarding logging, security, etc.
We were applying an error handling interceptor erroneously to all the routes but doc, this has been changed (see below)
We also included errors in the return spec for sync `lrs` methods, but did not catch and ensure these were included for the lib handling to use. Catching and passing of errors has been standardized across all sync method wrappers in `lrs.cljc` with the exception of `consistent-through`, which is called by an interceptor and functions differently.
Any error that is not explicitly handled by the `lrs` layer (a narrow class of specific named errors) will now be properly placed in the pedestal context map. Implementations can apply any error handling they wish by …

LRS-61 Remove Error Interceptor

---

deps.edn

Update cheshire and ring libraries to their latest versions in order to address CVE-2020-28491 and CVE-2021-29425, respectively.
(NOTE: There are still CVEs from ClojureScript, but they cannot be eliminated via updating and they don't affect Clojure downstream apps.)

Address CVEs in lrs lib

---

deps.edn

Pedestal has finally been updated! (See: https://github.com/pedestal/pedestal/pull/698)

Update Pedestal to v0.5.10

---

package-lock.json
src/main/deps.cljs

Does what it says on the tin.
Note that this change is applied to the `deps.cljs` file, `lrs` lacks a `package.json` of its own.
See https://github.com/yetanalytics/lrs/security/dependabot/4

lock minimist at 1.2.6 for CVE-2021-44906

---

src/main/com/yetanalytics/lrs/xapi/document.cljc

[LRS-59] When we [made adjustments to allow for missing content-type and length](https://github.com/yetanalytics/lrs/pull/69), I neglected to modify the content-type checking in `merge-or-replace` to account for missing ctypes (it runs `.length` assuming a string).
[LRS-59]: https://yet.atlassian.net/browse/LRS-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LRS-59 update merge-or-replace to handle missing ctypes

---

README.md
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements/attachment/response.cljc
src/main/com/yetanalytics/lrs/pedestal/routes/statements.cljc
src/main/com/yetanalytics/lrs/protocol.cljc
src/test/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements/attachment/response_test.cljc
src/test/com/yetanalytics/test_runner.cljc
src/test/com/yetanalytics/test_support.cljc

[LRS-68] ~~Currently the async multipart body build fn simply omits nil attachments. It should instead make the multipart result invalid, since the status cannot be changed. It is also currently utilized for sync responses, which is extra overhead.~~
~~Separating the sync and async approaches to building multipart responses (and testing them for parity) will let us have different behaviors WRT errors in mid-multipart on async.~~
After more research, the universal (sync + async) use of a channel body is probably more desirable as it allows even sync implementations to return things like `File` for attachment content which are passed for direct handling by pedestal.
This leaves the problem with the current impl that it simply omits attachments when errors occur, rather than terminating the …

LRS-68 Handle Async Multipart Errors

---

deps.edn
src/bench/com/yetanalytics/lrs/bench.clj
src/main/com/yetanalytics/lrs/pedestal/routes/statements.cljc
src/test/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements/attachment/response_test.cljc

We're getting a lot of deprecation warnings downstream for `to-chan`, it should be replaced with the explicitly non-blocking version `to-chan!`

LRS-66 Update core.async and replace deprecated functions

---

README.md
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements/attachment.cljc
src/main/com/yetanalytics/lrs/xapi/statements.cljc
src/test/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements/attachment_test.cljc
src/test/com/yetanalytics/lrs/xapi/statements_test.cljc
src/test/com/yetanalytics/lrs_test.clj
src/test/com/yetanalytics/test_runner.cljc

[LRS-72]
Currently lrs expects attachment requests to contain one attachment part for every attachment reference in statement data. The spec language is ambiguous in this regard:  https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#requirements-for-attachment-statement-batches
It does however say that LRPs should normalize/deduplicate attachments being sent, so LRS (and its impls) should handle this.
Example with multiple references + deduplicated attachments that currently fails on our system:
<details>
<summary>failing example</summary>
````http
POST /xapi/statements HTTP/1.1
X-Experience-API-Version: 1.0.3
Content-Type: multipart/mixed; boundary=105423a5219f5a63362a375ba7a64a8f234da19c7d01e56800c3c64b26bb2fa0
Authorization: 
Host: localhost:8080
Connection: close …
```

LRS-72 Handle deduplicated attachment multiparts

---

README.md
src/main/com/yetanalytics/lrs/pedestal/http/multipart_mixed.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc
src/main/com/yetanalytics/lrs/util.cljc
src/test/com/yetanalytics/lrs/pedestal/http/multipart_mixed_test.cljc

[LRS-74] [LRS-75] Apparently our clj multipart parsing allows _either_ a crlf or just an lf. That seems wrong! ~~Cljs is more discerning.~~ Actually it shared some of the same issues with boundary checking, and this is addressed now.
This PR:
* Requires proper CRLF line breaks per [RFC 1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html)
* Explicitly disallows preamble + epilogue text
* Properly verifies the presence of start + end boundaries
* Reworked clj `java.util.Scanner` implementation
* Transitioned cljs `clojure.string/split`-based strategy to explicit boundary mapping
* Adds an implementation note to the README
* Limits multipart body errors to a single keyword
* Removed reliance on runtime asserts
[LRS-74]: https://yet.atlassian.net/browse/LRS-74?atlOrigin=eyJpIjoiNWRkN …

LRS-75 Make multipart parsing more strict

---

deps.edn

Probably an FP, but we don't use it

exclude msgpack to clear CVE-2022-41719

---

src/test/com/yetanalytics/conformance_test/clj/async.clj
src/test/com/yetanalytics/conformance_test/clj/sync.clj
src/test/com/yetanalytics/conformance_test/cljs.clj

With the 2.0 conformance tests merged, they now default to 2.0.0 so lock the tests down to 1.0.3 which is what we currently support.

Lock conformance tests to 1.0.3

---

deps.edn
dev-resources/attachments/attachment_post_body.txt
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/document.cljc
src/main/com/yetanalytics/lrs/pedestal/interceptor/xapi/statements.cljc
src/main/com/yetanalytics/lrs/pedestal/routes.cljc
src/test/com/yetanalytics/conformance_test/clj/async.clj
src/test/com/yetanalytics/conformance_test/clj/sync.clj
src/test/com/yetanalytics/conformance_test/cljs.clj
src/test/com/yetanalytics/lrs/scan_test.clj
src/test/com/yetanalytics/test_runner.cljc
src/test/com/yetanalytics/test_support.cljc

[SQL-215] Allow impl-submitted `file-scanner` function to scan incoming attachments and documents.
[SQL-215]: https://yet.atlassian.net/browse/SQL-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-215 Support Attachment and Document Scanning

---

deps.edn
src/main/com/yetanalytics/lrs/pedestal/openapi.cljc

spec currently lists the POST method at /xapi/statements as taking `statementID`s; it should be listed as taking `Statement`s

fixes error in /xapi/statements POST openapi spec

---

src/main/com/yetanalytics/lrs/xapi/activities.cljc
src/test/com/yetanalytics/lrs/xapi/activities_test.cljc

`merge-activity`, originally designed as part of the in-memory LRS, would only accept merged updates to activity definition name and description.
This PR changes the merge function so that it allows replace-updates to scalar and array definition fields, with the exception of interaction activity fields. These are only updated atomically so they are cleared from the first activity definition prior to merge if they are at all present on the second.

modify merge-activity for improved upsert
